args:
  ctrl_space: ee
  ctrl_type: delta
  max_timesteps: 1800
  num_sequences: 1
  sequence_idx: -1
  show_gui: false
  task: task_D
  use_wrist: true
name: calvin_task_d_wrist
type: vlastudio.benchmark.calvin.CalvinEnv
