type: vlastudio.deploy.robot.sim_pybullet.AbsJointRobot
name: a1
args:
  name: a1
  max_size_mb: 64
  fps: 240.0
  control_shm_name: null
  robot_urdf_path: a1/a1.urdf
  initial_joint_positions: [0.0, 0.67, -1.3, 0.0, 0.67, -1.3, 0.0, 0.67, -1.3, 0.0, 0.67, -1.3]
  gripper_joint_indices: []
  gripper_width: 0.0
  use_gui: true
