type: vlastudio.deploy.robot.sim_pybullet.DeltaEERobot
name: kuka_iiwa_delta_ee
args:
  name: kuka_iiwa_delta_ee
  max_size_mb: 64
  fps: 240.0
  control_shm_name: null
  robot_urdf_path: kuka_iiwa/model.urdf
  ee_link_index: 6
  initial_joint_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  gripper_joint_indices: []
  gripper_width: 0.0
  use_gui: true
