type: vlastudio.deploy.robot.sim_pybullet.AbsJointRobot
name: pr2_gripper
args:
  name: pr2_gripper
  max_size_mb: 64
  fps: 240.0
  control_shm_name: null
  robot_urdf_path: pr2_gripper.urdf
  initial_joint_positions: [0.0, 0.0]
  gripper_joint_indices: [0, 1]
  gripper_width: 0.08
  use_gui: true
