type: vlastudio.deploy.robot.agilex_aloha.AgilexAloha
name: agilex_aloha
args:
  name: agilex_aloha
  max_size_mb: 64
  fps: 40.0
  control_shm_name: null
  init_pos:
    left:
      - -0.00133514404296875
      - 0.00209808349609375
      - 0.01583099365234375
      - -0.032616615295410156
      - -0.00286102294921875
      - 0.00095367431640625
      - 3.557830810546875
    right:
      - -0.00133514404296875
      - 0.00438690185546875
      - 0.034523963928222656
      - -0.053597450256347656
      - -0.00476837158203125
      - -0.00209808349609375
      - 3.557830810546875
  limit_pos:
    upper:
      - 2.6878
      - 3.4034
      - 0.0
      - 1.85
      - 1.3089
      - 1.7453
      - 7.0
      - 2.6878
      - 3.4034
      - 0.0
      - 1.85
      - 1.3089
      - 1.7453
      - 7.0
    lower:
      - -2.6878
      - 0.0
      - -3.0543
      - -1.85
      - -1.3089
      - -1.7453
      - 0.0
      - -2.6878
      - 0.0
      - -3.0543
      - -1.85
      - -1.3089
      - -1.7453
      - 0.0
  ros_operator:
    arm_steps_length:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.2
    img_front_depth_topic: /camera_f/depth/image_raw
    img_front_topic: /camera_f/color/image_raw
    img_left_depth_topic: /camera_l/depth/image_raw
    img_left_topic: /camera_l/color/image_raw
    img_right_depth_topic: /camera_r/depth/image_raw
    img_right_topic: /camera_r/color/image_raw
    publish_rate: 40
    puppet_arm_left_cmd_topic: /master/joint_left
    puppet_arm_left_topic: /puppet/joint_left
    puppet_arm_right_cmd_topic: /master/joint_right
    puppet_arm_right_topic: /puppet/joint_right
    robot_base_cmd_topic: /cmd_vel
    robot_base_topic: /odom_raw
    use_depth_image: false
    use_robot_base: false
