
- type: vlastudio.deploy.sensor.camera.opencv_camera.OpenCVCamera
  name: head_camera
  args:
    name: head_camera
    index_or_path: /dev/head_camera
    width: 640
    height: 480
    fps: 30
    max_size_mb: 10
    fourcc: MJPG

- type: vlastudio.deploy.sensor.camera.opencv_camera.OpenCVCamera
  name: left_wrist_camera
  args:
    name: left_wrist_camera
    index_or_path: /dev/left_camera
    width: 640
    height: 480
    max_size_mb: 10
    fps: 30
    fourcc: MJPG

# - type: vlastudio.deploy.sensor.camera.opencv_camera.OpenCVCamera
#   name: right_wrist_camera
#   args:
#     name: right_wrist_camera
#     index_or_path: /dev/right_camera
#     width: 640
#     height: 480
#     fps: 30
#     max_size_mb: 10
#     fourcc: MJPG
