type: vlastudio.deploy.robot.koch.KochFollowerWithCamera
name: koch_follower
args:
  name: koch_follower
  max_size_mb: 64
  fps: 100.0
  control_shm_name: null
  com: /dev/ttyACM1
  robot_id: koch_follower
  camera_configs:
    front_camera:
      index_or_path: /dev/video2
      width: 640
      height: 480
      fps: 30
