type: vlastudio.deploy.robot.so101.So101FollowerWithCamera
name: so101_follower
args:
  name: so101_follower
  max_size_mb: 64
  fps: 30.0
  control_shm_name: null
  com: COM4
  robot_id: so101_follower
  camera_configs:
    front_camera:
      index_or_path: 1
      width: 640
      height: 480
      fps: 30
