datasets:
- type: vlastudio.data_utils.datasets.lerobotv20_wrapper.WrappedLerobotV20Dataset
  name: lerobot_example_hil_serl_dataset
  args:
    dataset_path_list:
    - lerobot/example_hil_serl_dataset
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: delta
meta:
  action_dim: 4
  state_dim: 18
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
