datasets:
- type: vlastudio.data_utils.datasets.lerobotv20_wrapper.WrappedLerobotV20Dataset
  name: lerobot_svla_so100_sorting
  args:
    dataset_path_list:
    - lerobot/svla_so100_sorting
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: delta
meta:
  action_dim: 6
  state_dim: 6
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
