datasets:
- type: vlastudio.data_utils.datasets.lerobotv20_wrapper.WrappedLerobotV20Dataset
  name: lerobot_unitreeh1_warehouse
  args:
    dataset_path_list:
    - lerobot/unitreeh1_warehouse
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: delta
meta:
  action_dim: 40
  state_dim: 19
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
