datasets:
- type: vlastudio.data_utils.datasets.lerobotv20_wrapper.WrappedLerobotV20Dataset
  name: lerobot_xvla-soft-fold
  args:
    dataset_path_list:
    - lerobot/xvla-soft-fold
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: delta
meta:
  action_dim: 14
  state_dim: 96
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
