datasets:
- type: vlastudio.data_utils.datasets.lerobotv20_wrapper.WrappedLerobotV20Dataset
  name: lerobot_behavior1k-task0022
  args:
    dataset_path_list:
    - lerobot/behavior1k-task0022
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: delta
meta:
  action_dim: 23
  state_dim: 256
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
