datasets:
- type: vlastudio.data_utils.datasets.lerobot_wrapper.WrappedLerobotDataset
  name: lerobot_behavior1k-task0000
  args:
    dataset_path_list:
    - lerobot/behavior1k-task0000
    chunk_size: 50
    video_backend: pyav
    ctrl_space: joint
    ctrl_type: delta
    tolerance_s: 1.0
    image_size:
    - 256
    - 256
    camera_names: 
    - observation.images.rgb.left_wrist
    - observation.images.rgb.right_wrist
    - observation.images.rgb.head
meta:
  action_dim: 23
  state_dim: 256
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
