- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_0
  args:
    task: libero_spatial_0
    max_timesteps: 220
    ctrl_space: ee
    image_size:
    - 256
    - 256
    use_openvla_gripper: False
    use_wrist: True


- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_1
  args:
    task: libero_spatial_1
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256


- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_2
  args:
    task: libero_spatial_2
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256


- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_3
  args:
    task: libero_spatial_3
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256

    
- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_4
  args:
    task: libero_spatial_4
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256


- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_5
  args:
    task: libero_spatial_5
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256


- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_6
  args:
    task: libero_spatial_6
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256
    camera_ids:
    - 0

- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_7
  args:
    task: libero_spatial_7
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256
 

- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_8
  args:
    task: libero_spatial_8
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256

    
- type: vlastudio.benchmark.libero.LiberoEnv
  name: libero_spatial_9
  args:
    task: libero_spatial_9
    max_timesteps: 220
    ctrl_space: ee
    use_wrist: True
    image_size:
    - 256
    - 256
