datasets:
- type: vlastudio.data_utils.datasets.lerobotv20_wrapper.WrappedLerobotV20Dataset
  name: lerobot_cmu_stretch
  args:
    dataset_path_list:
    - lerobot/cmu_stretch
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: delta
meta:
  action_dim: 8
  state_dim: 4
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
