datasets:
- type: vlastudio.data_utils.datasets.WrappedLerobotDataset
  name: lerobot_droid_v30
  args:
    dataset_path_list:
    - cadene/droid_1.0.1_v30
    camera_names:
      - observation.images.exterior_1_left
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: abs
    # no_ensure_download: true
    video_backend: pyav
    # episode_filter:
    #   invalid_episode_index: [8056, 9085, 11907, 14419, 17536, 18325, 55276, 59341, 64837, 64871]
meta:
  action_dim: 8
  state_dim: 8
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
