datasets:
- type: vlastudio.data_utils.datasets.lerobotv20_wrapper.WrappedLerobotV20Dataset
  name: furniture_bench_dataset_lerobot
  args:
    dataset_path_list:
    - IPEC-COMMUNITY/furniture_bench_dataset_lerobot
    chunk_size: 50
    ctrl_space: ee
    ctrl_type: abs
meta:
  action_dim: 7
  state_dim: 7
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
