datasets:
- type: vlastudio.data_utils.datasets.lerobotv20_wrapper.WrappedLerobotV20Dataset
  name: lerobot_usc_cloth_sim
  args:
    dataset_path_list:
    - lerobot/usc_cloth_sim
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: delta
meta:
  action_dim: 4
  state_dim: 1
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
