type: vlastudio.benchmark.aloha.AlohaSimEnv
name: aloha_transfer
args:
  task: sim_transfer_cube_scripted
  max_timesteps: 400
  ctrl_space: joint
  ctrl_type: abs
  camera_ids: [0]
  image_size: [640, 480]
runtime:
  python: "3.10"
  requirements:
    - dm-control==1.0.34
    - mujoco==3.3.6
