datasets:
- type: vlastudio.data_utils.datasets.lerobotv21_wrapper.WrappedLerobotV21Dataset
  name: bigym_dishwasher_close_trays
  args:
    dataset_path_list:
    - WWZzz/bigym_dishwasherclosetrays
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: abs
    state_key: observation.state      # bimanual arm proprioception
    action_key: action
    camera_names:                     # 3 cameras: head + 2 wrists
      - observation.images.head
      - observation.images.left_wrist
      - observation.images.right_wrist
meta:
  action_dim: 16                       # action dimension from bigym
  state_dim: 16                        # proprioception qpos+qvel (may vary)
  action_normalize: zscore
  state_normalize: zscore
