# This configuration is only for debug the vqa dataset loading

datasets:
- type: vlastudio.data_utils.datasets.AlohaSimDataset
  name: sim_transfer_cube_scripted
  args:
    dataset_path_list:
    - data/sim_transfer_cube_scripted
    camera_names:
    - primary
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: abs
    preload_data: true

vqa:
- type: vlastudio.data_utils.vqa.daquar.DAQUARDataset
  name: daquar

transforms:
- type: vlastudio.data_utils.transform.ImageResizeTransform
  args:
    size: [640, 480]

# Task metadata
meta:
  action_dim: 14
  state_dim: 14
  image_size: [640, 480]
  action_normalize: zscore
  state_normalize: zscore

sample_weights:
  daquar: 5.0
  sim_transfer_cube_scripted: 1.0