datasets:
- type: data_utils.datasets.robomind_dataset.RoboMindDataset
  name: robomind_agilex_3rgb-3_eggplantOven_ee
  args:
    dataset_path_list:
    - /inspire/dataset/robomind/lerobot/benchmark1_0_release/agilex_3rgb/3_eggplantOven
    chunk_size: 50
    ctrl_space: ee
    ctrl_type: abs
meta:
  action_dim: 16
  state_dim: 16
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
