datasets:
- type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
  name: robomind_franka_3rgb-put_the_cucumber_on_the_left_side_of_the_bowl_ee
  args:
    dataset_path_list:
    - /inspire/dataset/robomind/lerobot/benchmark1_1_release/franka_3rgb/put_the_cucumber_on_the_left_side_of_the_bowl
    chunk_size: 50
    ctrl_space: ee
    ctrl_type: abs
meta:
  action_dim: 7
  state_dim: 7
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
