datasets:
- type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
  name: robomind_tienkung_xsens_1rgb-plug_insertion_ee
  args:
    dataset_path_list:
    - /inspire/dataset/robomind/lerobot/benchmark1_0_release/tienkung_xsens_1rgb/plug_insertion
    chunk_size: 50
    ctrl_space: ee
    ctrl_type: abs
meta:
  action_dim: 12
  state_dim: 12
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
