[project]
name = "ilstd-bigym"
version = "0.1.0"
description = "BiGym environment integration for ILStudio"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "loguru",
    "tianshou==0.2.0",
    "numpy==1.26.*",
    "safetensors==0.3.3",
    "mujoco==3.1.5",
    "dm_control==1.0.19",
    "imageio",
    "pyquaternion",
    "mujoco_utils",
    "wget",
    "pyyaml",
    "dearpygui",
    "gymnasium @ git+https://git@github.com/stepjam/Gymnasium.git@0.29.2",
    "mojo @ git+https://git@github.com/stepjam/mojo.git@0.1.1",
    "lerobot==0.3.3",
]

[tool.uv]
default-groups = []

