datasets:
- type: vlastudio.data_utils.datasets.rlds_wrapper.WrappedRLDSDataset
  name: libero_obj_rlds
  args:
    dataset_dir: /inspire/qb-dev/project/robot-action/public/huggingface/hub/datasets--openvla--modified_libero_rlds/snapshots/6ce6aaaaabdbe590b1eef5cd29c0d33f14a08551
    data_mix: libero_object_no_noops
    chunk_size: 50
    image_size:
    - 256
    - 256
meta:
  action_dim: 7
  state_dim: 8
  action_normalize: zscore
  state_normalize: zscore
