type: vlastudio.benchmark.tabletop_sim.TabletopSimEnv
name: tabletop_sim_dish_drainer
args:
  task: aloha_dish_drainer
  action_space: joint_pos
  ctrl_space: joint
  ctrl_type: abs
  max_timesteps: 250        # episode_len=10s / DT=0.04
  camera_names:
    - agentview             # alias of simulator's 'back' view
    - wrist_left
    - wrist_right
  image_size: [640, 480]    # [width, height]
