type: vlastudio.benchmark.tabletop_sim.TabletopSimEnv
name: tabletop_sim_dish_drainer_new
args:
  task: aloha_dish_drainer_new
  action_space: joint_pos
  ctrl_space: joint
  ctrl_type: abs
  max_timesteps: 250        # episode_len=10s / DT=0.04
  camera_names:
    - agentview
    - wrist_left
    - wrist_right
  image_size: [640, 480]

