type: vlastudio.benchmark.tabletop_sim.TabletopSimEnv
name: tabletop_sim_shoes_table
args:
  task: aloha_shoes_table
  action_space: joint_pos
  ctrl_space: joint
  ctrl_type: abs
  max_timesteps: 375        # episode_len=15s / DT=0.04
  camera_names:
    - agentview             # alias of simulator's 'back' view
    - wrist_left
    - wrist_right
  image_size: [640, 480]    # [width, height]

