datasets:
- robomind_franka_fr3_dual_all:
  - type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
    name: robomind_franka_fr3_dual-both_pour_water
    args:
      dataset_path_list:
      - /inspire/dataset/robomind/lerobot/benchmark1_1_release/franka_fr3_dual/both_pour_water
      chunk_size: 50
      ctrl_space: joint
      ctrl_type: abs
  - type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
    name: robomind_franka_fr3_dual-left_place_gray_plate_from_low_rack_on_left_of_table
    args:
      dataset_path_list:
      - /inspire/dataset/robomind/lerobot/benchmark1_1_release/franka_fr3_dual/left_place_gray_plate_from_low_rack_on_left_of_table
      chunk_size: 50
      ctrl_space: joint
      ctrl_type: abs
  - type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
    name: robomind_franka_fr3_dual-left_place_gray_plate_on_lower_rack
    args:
      dataset_path_list:
      - /inspire/dataset/robomind/lerobot/benchmark1_1_release/franka_fr3_dual/left_place_gray_plate_on_lower_rack
      chunk_size: 50
      ctrl_space: joint
      ctrl_type: abs
  - type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
    name: robomind_franka_fr3_dual-left_push_plate_to_right_of_table
    args:
      dataset_path_list:
      - /inspire/dataset/robomind/lerobot/benchmark1_1_release/franka_fr3_dual/left_push_plate_to_right_of_table
      chunk_size: 50
      ctrl_space: joint
      ctrl_type: abs
  - type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
    name: robomind_franka_fr3_dual-right_slide_close_drawer
    args:
      dataset_path_list:
      - /inspire/dataset/robomind/lerobot/benchmark1_1_release/franka_fr3_dual/right_slide_close_drawer
      chunk_size: 50
      ctrl_space: joint
      ctrl_type: abs
  - type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
    name: robomind_franka_fr3_dual-right_slide_open_drawer
    args:
      dataset_path_list:
      - /inspire/dataset/robomind/lerobot/benchmark1_1_release/franka_fr3_dual/right_slide_open_drawer
      chunk_size: 50
      ctrl_space: joint
      ctrl_type: abs
meta:
  action_dim: 16
  state_dim: 16
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
