datasets:
- type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
  name: robomind_franka_3rgb-close_cap_trash_can_2
  args:
    dataset_path_list:
    - /inspire/dataset/robomind/lerobot/benchmark1_0_release/franka_3rgb/close_cap_trash_can_2
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: abs
meta:
  action_dim: 8
  state_dim: 8
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
