datasets:
- type: vlastudio.data_utils.datasets.robomind_dataset.RoboMindDataset
  name: robomind_ur_1rgb-put_egg_in_top_white_drawer
  args:
    dataset_path_list:
    - /inspire/dataset/robomind/lerobot/benchmark1_0_release/ur_1rgb/put_egg_in_top_white_drawer
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: abs
meta:
  action_dim: 7
  state_dim: 7
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
