datasets:
- type: vlastudio.data_utils.datasets.rlds_wrapper.WrappedRLDSDataset
  name: bc_z
  args:
    dataset_dir: /inspire/hdd/global_public/public_datas/Robotics_Related/Open-X-Embodiment/openx/
    data_mix: bc_z
    chunk_size: 16
    image_size:
    - 256
    - 256
- type: vlastudio.data_utils.datasets.rlds_wrapper.WrappedRLDSDataset
  name: berkeley_autolab_ur5
  args:
    dataset_dir: /inspire/hdd/global_public/public_datas/Robotics_Related/Open-X-Embodiment/openx/
    data_mix: berkeley_autolab_ur5
    chunk_size: 16
    image_size:
    - 256
    - 256
- type: vlastudio.data_utils.datasets.rlds_wrapper.WrappedRLDSDataset
  name: taco_play
  args:
    dataset_dir: /inspire/hdd/global_public/public_datas/Robotics_Related/Open-X-Embodiment/openx/
    data_mix: taco_play
    chunk_size: 16
    image_size:
    - 256
    - 256
meta:
  action_dim: 7
  state_dim: 8
  action_normalize: percentile
  state_normalize: percentile
