datasets:
- type: vlastudio.data_utils.datasets.WrappedLerobotDataset
  name: rlbench_block_pyramid
  args:
    dataset_path_list:
    - WWZzz/rlbench_block_pyramid
    chunk_size: 50
    ctrl_space: ee
    ctrl_type: abs
    video_backend: pyav
    camera_names: 
      - observation.images.overhead
      - observation.images.wrist
    state_key: observation.state.ee
    action_key: action.ee
meta:
  action_dim: 8
  state_dim: 8
  action_normalize: zscore
  state_normalize: zscore
